const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';

const RECORD_CONTACTS = 'RECORD_CONTACTS';
const ADD_CONTACT = 'ADD_CONTACT';
const EDIT_CONTACT = 'EDIT_CONTACT';
const DELETE_CONTACT = 'DELETE_CONTACT';
const CLEAR_CONTACTS = 'CLEAR_CONTACTS';

const UPDATE_MODAL = 'UPDATE_MODAL';

const UPDATE_SEARCH = 'UPDATE_SEARCH';
const RESET_SEARCH = 'RESET_SEARCH';

export {
  SIGN_IN,
  SIGN_OUT,
  RECORD_CONTACTS,
  ADD_CONTACT,
  EDIT_CONTACT,
  DELETE_CONTACT,
  CLEAR_CONTACTS,
  UPDATE_MODAL,
  UPDATE_SEARCH,
  RESET_SEARCH,
};
